package FOS_TEST.DATA_TESTS;

import FOS_CORE.Order;
import FOS_CORE.Rating;
import FOS_DATA.RatingRepository;
import org.junit.jupiter.api.*;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

public class RatingRepositoryTest {

    private RatingRepository ratingRepository;

    @BeforeEach
    void setUp() {
        ratingRepository = new RatingRepository();
    }

    @Test
    void testFetchRatingsForOrderWithExistingRatings() {
        // Order 1 already has a rating in your DB (5 stars, "Great pizza!")
        int orderId = 1;

        ArrayList<Rating> ratings = ratingRepository.fetchOrderRatings(new Order(orderId));

        assertNotNull(ratings, "Ratings list should not be null");
        assertFalse(ratings.isEmpty(), "Order 1 should have at least one rating");

        Rating r = ratings.get(0);
        assertEquals(5, r.getRatingValue(), "Rating value should match existing DB value");
        assertEquals("Great pizza!", r.getRatingComment(), "Rating comment should match DB value");
    }

    @Test
    void testFetchRatingsForOrderWithNoRatings() {
        // Order 2 has NO ratings in your DB
        int orderId = 2;

        ArrayList<Rating> ratings = ratingRepository.fetchOrderRatings(new Order(orderId));

        assertNotNull(ratings, "Ratings list should not be null");
        assertEquals(0, ratings.size(), "Order 2 should return an empty rating list");
    }

    @Test
    void testInsertNewRatingSuccessfully() {
        // Use an order with no ratings → Order 11
        int orderId = 11;

        Rating rating = new Rating();
        rating.setOrderId(orderId);
        rating.setRatingValue(5);
        rating.setRatingComment("Excellent!");

        boolean inserted = ratingRepository.insertOrderRating(rating);

        assertTrue(inserted, "Rating should be inserted successfully");
        assertTrue(rating.getRatingId() > 0, "Rating ID must be generated by DB");

        // Now fetch and validate
        ArrayList<Rating> ratings = ratingRepository.fetchOrderRatings(new Order(orderId));

        assertEquals(1, ratings.size(), "Order 11 should now have exactly one rating");

        Rating r = ratings.get(0);
        assertEquals(5, r.getRatingValue());
        assertEquals("Excellent!", r.getRatingComment());
    }

    @Test
    void testInsertRatingInvalidOrderFails() {
        // 9999 is a non-existent order → should fail due to FK constraint
        Rating rating = new Rating();
        rating.setOrderId(9999);
        rating.setRatingValue(4);
        rating.setRatingComment("Invalid order test");

        boolean result = ratingRepository.insertOrderRating(rating);

        assertFalse(result, "Rating insertion for nonexistent order should fail");
    }

    @Test
    void testMultipleRatingsForOrder() {
        // Order 12 has NO ratings → safe for multiple inserts
        int orderId = 12;

        Rating r1 = new Rating();
        r1.setOrderId(orderId);
        r1.setRatingValue(4);
        r1.setRatingComment("First rating");

        Rating r2 = new Rating();
        r2.setOrderId(orderId);
        r2.setRatingValue(5);
        r2.setRatingComment("Second rating");

        boolean insert1 = ratingRepository.insertOrderRating(r1);
        boolean insert2 = ratingRepository.insertOrderRating(r2);

        assertTrue(insert1, "First rating insert must succeed");
        assertTrue(insert2, "Second rating insert must succeed");

        ArrayList<Rating> ratings = ratingRepository.fetchOrderRatings(new Order(orderId));

        assertEquals(2, ratings.size(), "Order 12 should now have exactly 2 ratings");
    }
}
